import { CROSS_AGENT_CONTEXT_ORDER } from "../utils/config.js";

export function buildAgentContent(agentName, state = {}) {
  const rows = [
    `# ForgeMind Context for ${agentName}`,
    "",
    "Use this repository's generated context and memory before broad search.",
    "",
    "## Project Context Pointer",
    "",
    "- Start with generated context under `.codex/context/`.",
    "- Use repository memory under `.codex/memory/` for prior sessions, decisions, failures, fixes, and rationale.",
    "- Read source files only after using these pointers to identify the smallest relevant file set.",
    "",
    "## Read Order",
    ""
  ];
  CROSS_AGENT_CONTEXT_ORDER.forEach((file, index) => rows.push(`${index + 1}. ${file}`));
  rows.push(
    "",
    "## Agent Behavior",
    "",
    "- Prefer generated context and memory before broad repository scans.",
    "- Use context files to choose targeted source files.",
    "- Keep changes small and consistent with existing patterns.",
    "- Update `.codex/memory/` after durable decisions, failures, fixes, or handoff-worthy progress.",
    "",
    "## Safety",
    "",
    "- Source code remains the source of truth.",
    "- Generated context and memory can be stale; verify against source code before changing behavior.",
    "- Do not paste secrets or full source dumps into memory files.",
    "",
    "Generated by ForgeMind.",
    ""
  );
  return rows.join("\n");
}
